### ISSUE TITLE
🐛 [BUG] - Duplicate entries

### ISSUE THREAD

**Issue by matildaperuzzo** [Seshat-Global-History-Databank/seshat_api#20]
### Description

Something I noticed collating the new dataset template. Some entries seem to be duplicated. 
In the example below the line with id 571 appears twice.

### Reproduction steps

```py
import pandas as pd
from seshat_api import SeshatAPI
from seshat_api.sc import PolityTerritories

client = SeshatAPI(base_url="https://seshatdata.com/api")

territories = PolityTerritories(client)
territories_df = pd.DataFrame(territories.get_all())

territories_df[territories_df.polity.apply(lambda x: x['new_name'])=='iq_abbasid_cal_1']
```

### Error message

```bash
No error message
```

### Definition of Done

- [ ] A fix for the bug has been developed on a branch.
- [ ] A pull request has been created for the new branch to be merged into the main branch.

**Comment by kallewesterling** [comment]
An open question here, emerging from chats that we had last week, is whether this is is something that's a problem with the API Django app itself (i.e. this issue is actually related to the Seshat Django package) or whether it's emerging from the Python bindings to the API Django app (i.e. the issue is related to this repo).

**Comment by edwardchalstrey1** [comment]
Result of Matilda's pandas query above, showing the duplication of **571**:

```
territories_df[territories_df.polity.apply(lambda x: x['new_name'])=='iq_abbasid_cal_1']
      id  year_from  year_to  ...                           private_comment citations  curator
113  570      800.0    800.0  ...  {'id': 1, 'text': 'NO_PRIVATE_COMMENTS'}        []       []
128  571      900.0    900.0  ...  {'id': 1, 'text': 'NO_PRIVATE_COMMENTS'}        []       []
130  571      900.0    900.0  ...  {'id': 1, 'text': 'NO_PRIVATE_COMMENTS'}        []       []
```

[This query](https://seshatdata.com/api/sc/polity-territories/?year_to__range=900%2C900&year_to=&year_to__lte=&year_to__gte=&year_from__range=900%2C900&year_from=&year_from__lte=&year_from__gte=&description__icontains=&note__icontains=&finalized=&created_date__range=&created_date__date=&created_date__date__lte=&created_date__date__gte=&modified_date__range=&modified_date__date=&modified_date__date__lte=&modified_date__date__gte=&tag=&is_disputed=&is_uncertain=&expert_reviewed=&drb_reviewed=&polity__name__icontains=&polity__polity_tag=&polity__home_nga__name__icontains=&polity__home_nga__latitude__range=&polity__home_nga__latitude=&polity__home_nga__latitude__lte=&polity__home_nga__latitude__gte=&polity__home_nga__longitude__range=&polity__home_nga__longitude=&polity__home_nga__longitude__lte=&polity__home_nga__longitude__gte=&polity__home_seshat_region__mac_region__name=&polity__home_seshat_region__mac_region__name__icontains=&polity_territory_from=&polity_territory_from__gte=&polity_territory_from__lte=&polity_territory_to=&polity_territory_to__gte=&polity_territory_to__lte=&name=&name__icontains=) (I had to use the `year_from` and `year_to` set to 900 as there isn't a way to filter on `polity->new_name` I could see) appears to show that there is only one result with the ID 571, suggesting the bug is with the Python package - I'll investigate further

**Comment by edwardchalstrey1** [comment]
Ok, I think this is just down to the `get_all` function not being careful enough, will open a PR with fix
